packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

# Цей файл pnpm-workspace.yaml потрібен для того, щоб об'єднати кілька Node.js-проєктів в один workspace.Тепер pnpm знає, що це один великий проєкт із кількох пакетів.
