export enum Permission {
  WORKSPACE_UPDATE = "WORKSPACE_UPDATE",

  WORKSPACE_DELETE = "WORKSPACE_DELETE",

  MEMBER_INVITE = "MEMBER_INVITE",

  MEMBER_REMOVE = "MEMBER_REMOVE",

  ROLE_UPDATE = "ROLE_UPDATE",

  PROJECT_CREATE = "PROJECT_CREATE",

  PROJECT_UPDATE = "PROJECT_UPDATE",

  PROJECT_DELETE = "PROJECT_DELETE",

  TASK_CREATE = "TASK_CREATE",

  TASK_UPDATE = "TASK_UPDATE",

  TASK_DELETE = "TASK_DELETE",

  COMMENT_CREATE = "COMMENT_CREATE",
}